In [1]:
import numpy as np

In [14]:
a = np.array([[0,0,0]])

a = np.append(a, [[1,1,1]])
print(a)

[0 0 0 1 1 1]


In [29]:
shape = (1, 2, 3)
b = np.ones(shape)
empty_line = np.zeros(shape)
b = np.vstack((b, empty_line))

cnt = 0
row_cnt = 0


for row in b:
    led_cnt = 0
    for led in row:
        color_cnt = 0
        for color in led:
            b[row_cnt][led_cnt][color_cnt] = cnt
            cnt += 1
            color_cnt += 1
        led_cnt += 1
    row_cnt += 1

print(b)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [30]:
print(b[1][0][2])

8.0


In [16]:
a = np.array([[1,2,3],
              [4,5,6]])

b = 0
for row in a: b += len(row)
print(b)

6


In [21]:
a[0:, 1:]

array([[2, 3],
       [5, 6]])

In [26]:
a.size

6

In [35]:
led_matrix = np.array([[4, 15, 24, 35, 5, 14, 25, 34], 
                        [3, 16, 23, 36, 6, 13, 26, 33],
                        [2, 17, 22, 37, 7, 12, 27, 32],
                        [1, 18, 21, 38, 8, 11, 28, 31],
                        [0, 19, 20, 39, 9, 10, 29, 30]])

a = led_matrix[2:, 0:2]
a = a.flatten()



array([ 2, 17,  1, 18,  0, 19])

In [15]:
# Create an empty dictionary
d = {}

# Set the number of entries
n = 10

# Add entries to the dictionary
for i in range(n):
    d[i] = {}
    for j in range(20):
        d[i][j] = i * j

import json

# Open the file in write mode
with open("dict.txt", "w") as f:
    # Write the dictionary to the file
    f.write("test \n")
with open("dict.txt", "a") as f:
    # Write the dictionary to the file
    for step in d:
        print(d[step])
        json.dump(d[step], f)
        f.write("\n")

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19}
{0: 0, 1: 2, 2: 4, 3: 6, 4: 8, 5: 10, 6: 12, 7: 14, 8: 16, 9: 18, 10: 20, 11: 22, 12: 24, 13: 26, 14: 28, 15: 30, 16: 32, 17: 34, 18: 36, 19: 38}
{0: 0, 1: 3, 2: 6, 3: 9, 4: 12, 5: 15, 6: 18, 7: 21, 8: 24, 9: 27, 10: 30, 11: 33, 12: 36, 13: 39, 14: 42, 15: 45, 16: 48, 17: 51, 18: 54, 19: 57}
{0: 0, 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 7: 28, 8: 32, 9: 36, 10: 40, 11: 44, 12: 48, 13: 52, 14: 56, 15: 60, 16: 64, 17: 68, 18: 72, 19: 76}
{0: 0, 1: 5, 2: 10, 3: 15, 4: 20, 5: 25, 6: 30, 7: 35, 8: 40, 9: 45, 10: 50, 11: 55, 12: 60, 13: 65, 14: 70, 15: 75, 16: 80, 17: 85, 18: 90, 19: 95}
{0: 0, 1: 6, 2: 12, 3: 18, 4: 24, 5: 30, 6: 36, 7: 42, 8: 48, 9: 54, 10: 60, 11: 66, 12: 72, 13: 78, 14: 84, 15: 90, 16: 96, 17: 102, 18: 

In [6]:
import numpy as np

color = np.array([[1, 1, 1]])
color2 = np.array([[[1, 1, 1], [2, 2, 2]],
                   [[3, 3, 3], [4, 4, 4]]])

color2.ndim

3

In [20]:

color2 = color2.reshape(-1, color2.shape[-1])
color2.flatten()


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [23]:
a = [0,2,31,1,1,1,1]
for i, idx in enumerate(a):
    print(i)

0
1
2
3
4
5
6


In [22]:
import math
# Calculate the sine of an angle in degrees
angle_degrees = 45
angle_radians = math.radians(angle_degrees)
sine = math.sin(angle_radians)
print(sine)  # Output: 0.7071067811865475

0.7071067811865476
